name: Misspells
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: reviewdog/action-misspell@v1
        with:
          locale: "US"
          level: error
